message(STATUS "External project: SDL2")
message(STATUS "INSTALL_DEPENDENCIES_DIR: ${INSTALL_DEPENDENCIES_DIR}")

set(SDL2_PREFIX "${INSTALL_DEPENDENCIES_DIR}/sdl_prefix") 
set(SDL2_INSTALL_DIR "${INSTALL_DEPENDENCIES_DIR}/sdl") 

ExternalProject_Add(SDL2_EXTERNAL 
    PREFIX ${SDL2_PREFIX} 
    URL https://www.libsdl.org/release/SDL2-2.0.8.zip
    INSTALL_DIR ${SDL2_INSTALL_DIR} 
    CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${SDL2_INSTALL_DIR} -DSDL_SHARED=ON -DSDL_STATIC=ON
	
	LOG_DOWNLOAD ON
	LOG_UPDATE ON
	LOG_CONFIGURE ON 
	LOG_BUILD ON
	LOG_INSTALL ON 
) 

message(STATUS "SDL2_PREFIX: ${SDL2_PREFIX}")
message(STATUS "SDL2_INSTALL_DIR: ${SDL2_INSTALL_DIR}")